# Generated by Django 4.2.7 on 2023-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5000)),
                ('singer', models.CharField(max_length=5000)),
                ('tags', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='images')),
                ('song', models.FileField(upload_to='images')),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
